# Generated by Django 3.2 on 2023-06-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
